/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	autoscalingv1 "multidim-pod-autoscaler/pkg/apis/autoscaling/v1"
	versioned "multidim-pod-autoscaler/pkg/client/clientset/versioned"
	internalinterfaces "multidim-pod-autoscaler/pkg/client/informers/externalversions/internalinterfaces"
	v1 "multidim-pod-autoscaler/pkg/client/listers/autoscaling/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MultidimPodAutoscalerInformer provides access to a shared informer and lister for
// MultidimPodAutoscalers.
type MultidimPodAutoscalerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MultidimPodAutoscalerLister
}

type multidimPodAutoscalerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMultidimPodAutoscalerInformer constructs a new informer for MultidimPodAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMultidimPodAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMultidimPodAutoscalerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMultidimPodAutoscalerInformer constructs a new informer for MultidimPodAutoscaler type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMultidimPodAutoscalerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1().MultidimPodAutoscalers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutoscalingV1().MultidimPodAutoscalers(namespace).Watch(context.TODO(), options)
			},
		},
		&autoscalingv1.MultidimPodAutoscaler{},
		resyncPeriod,
		indexers,
	)
}

func (f *multidimPodAutoscalerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMultidimPodAutoscalerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *multidimPodAutoscalerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&autoscalingv1.MultidimPodAutoscaler{}, f.defaultInformer)
}

func (f *multidimPodAutoscalerInformer) Lister() v1.MultidimPodAutoscalerLister {
	return v1.NewMultidimPodAutoscalerLister(f.Informer().GetIndexer())
}
