/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	autoscalingv1 "multidim-pod-autoscaler/pkg/apis/autoscaling/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultidimPodAutoscalers implements MultidimPodAutoscalerInterface
type FakeMultidimPodAutoscalers struct {
	Fake *FakeAutoscalingV1
	ns   string
}

var multidimpodautoscalersResource = schema.GroupVersionResource{Group: "autoscaling.k8s.io", Version: "v1", Resource: "multidimpodautoscalers"}

var multidimpodautoscalersKind = schema.GroupVersionKind{Group: "autoscaling.k8s.io", Version: "v1", Kind: "MultidimPodAutoscaler"}

// Get takes name of the multidimPodAutoscaler, and returns the corresponding multidimPodAutoscaler object, and an error if there is any.
func (c *FakeMultidimPodAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *autoscalingv1.MultidimPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multidimpodautoscalersResource, c.ns, name), &autoscalingv1.MultidimPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.MultidimPodAutoscaler), err
}

// List takes label and field selectors, and returns the list of MultidimPodAutoscalers that match those selectors.
func (c *FakeMultidimPodAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *autoscalingv1.MultidimPodAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multidimpodautoscalersResource, multidimpodautoscalersKind, c.ns, opts), &autoscalingv1.MultidimPodAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &autoscalingv1.MultidimPodAutoscalerList{ListMeta: obj.(*autoscalingv1.MultidimPodAutoscalerList).ListMeta}
	for _, item := range obj.(*autoscalingv1.MultidimPodAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multidimPodAutoscalers.
func (c *FakeMultidimPodAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multidimpodautoscalersResource, c.ns, opts))

}

// Create takes the representation of a multidimPodAutoscaler and creates it.  Returns the server's representation of the multidimPodAutoscaler, and an error, if there is any.
func (c *FakeMultidimPodAutoscalers) Create(ctx context.Context, multidimPodAutoscaler *autoscalingv1.MultidimPodAutoscaler, opts v1.CreateOptions) (result *autoscalingv1.MultidimPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multidimpodautoscalersResource, c.ns, multidimPodAutoscaler), &autoscalingv1.MultidimPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.MultidimPodAutoscaler), err
}

// Update takes the representation of a multidimPodAutoscaler and updates it. Returns the server's representation of the multidimPodAutoscaler, and an error, if there is any.
func (c *FakeMultidimPodAutoscalers) Update(ctx context.Context, multidimPodAutoscaler *autoscalingv1.MultidimPodAutoscaler, opts v1.UpdateOptions) (result *autoscalingv1.MultidimPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multidimpodautoscalersResource, c.ns, multidimPodAutoscaler), &autoscalingv1.MultidimPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.MultidimPodAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMultidimPodAutoscalers) UpdateStatus(ctx context.Context, multidimPodAutoscaler *autoscalingv1.MultidimPodAutoscaler, opts v1.UpdateOptions) (*autoscalingv1.MultidimPodAutoscaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(multidimpodautoscalersResource, "status", c.ns, multidimPodAutoscaler), &autoscalingv1.MultidimPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.MultidimPodAutoscaler), err
}

// Delete takes name of the multidimPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeMultidimPodAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multidimpodautoscalersResource, c.ns, name), &autoscalingv1.MultidimPodAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultidimPodAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multidimpodautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &autoscalingv1.MultidimPodAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched multidimPodAutoscaler.
func (c *FakeMultidimPodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingv1.MultidimPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multidimpodautoscalersResource, c.ns, name, pt, data, subresources...), &autoscalingv1.MultidimPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.MultidimPodAutoscaler), err
}
