---
apiVersion: autoscaling.k8s.io/v1
kind: MultidimPodAutoscaler
metadata:
  name: test-mpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: mpa-test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpa-test-app
  labels:
    app: mpa-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpa-test-app
  template:
    metadata:
      labels:
        app: mpa-test-app
    spec:
      containers:
        - image: aliverjon/cpu-bound-amd64:latest
          imagePullPolicy: Always
          name: metrics-provider
          ports:
            - name: metrics
              containerPort: 8081
            - name: compute
              containerPort: 8082
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mpa-test-app
  name: mpa-test-app
spec:
  ports:
    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: compute
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: mpa-test-app
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mpa-test-app
  labels:
    app: mpa-test-app
spec:
  selector:
    matchLabels:
      app: mpa-test-app
  endpoints:
    - port: metrics